theme:
  light: [flatly, _quarto/i2ml_theme.scss]
  dark: [darkly, _quarto/i2ml_theme.scss]
format: 
  html:
    toc: true
    code-fold: false
    mathspec: true
    latex_engine: pdflatex
    embed-resources: true
    css: _quarto/evaluation-styles.css
    format-links: false
  pdf:
    include-in-header:
      file: _quarto/pdf-preamble.tex
filters:
  - _quarto/indent_filter.lua
jupyter: python3
notebook-links: global

