theme:
  light: [flatly, _quarto/i2ml_theme.scss]
  dark: [darkly, _quarto/i2ml_theme.scss]
format: 
  html:
    toc: true
    code-fold: false
    mathspec: true
    latex_engine: pdflatex
jupyter: python3
notebook-links: global

